In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
import numpy as np

ysArray = [1, 2, 3, 4, 5, 6, 7]
print("ysArray:\n{}".format(ysArray))

ysArray:
[1, 2, 3, 4, 5, 6, 7]


In [5]:
ysArray

[1, 2, 3, 4, 5, 6, 7]

In [10]:
arr1 = np.array(ysArray)
print(arr1)
arr1
arr1.shape # arr1의 형태(크기: 열과 행) 확인

[1 2 3 4 5 6 7]


array([1, 2, 3, 4, 5, 6, 7])

(7,)

In [13]:
arr2 = np.array([1, 2, 3, 4])
arr2
arr2.shape
arr2.dtype # arr2의 data type 확인

array([1, 2, 3, 4])

(4,)

dtype('int64')

In [14]:
data2 = [1, 2, 3.14, 4]
data2

[1, 2, 3.14, 4]

In [15]:
arr3 = np.array(data2)
arr3
arr3.dtype

array([1.  , 2.  , 3.14, 4.  ])

dtype('float64')

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(9)      # 1로 원소를 채운 길이 9짜리 배열 생성
np.ones((3, 2)) # 1로 원소를 채운 3x2 행렬 생성

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# arange: 1씩 증가하는 list 생성
np.arange(3)
np.arange(4, 9)

array([0, 1, 2])

array([4, 5, 6, 7, 8])

In [23]:
arr1 = np.array([[9, 8, 7], [6, 5, 4]])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])
arr1
arr2
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2

array([[9, 8, 7],
       [6, 5, 4]])

array([[10, 20, 30],
       [40, 50, 60]])

array([[19, 28, 37],
       [46, 55, 64]])

array([[ -1, -12, -23],
       [-34, -45, -56]])

array([[ 90, 160, 210],
       [240, 250, 240]])

array([[0.9       , 0.4       , 0.23333333],
       [0.15      , 0.1       , 0.06666667]])

In [ ]:
arr2
arr3 = np.array([17, 17, 17])
arr3
# 크기가 다른 list 간의 연산 지원(브로드캐스티드)
arr2 + arr3 # arr2 각 행렬 모든 원소에 arr3 원소를 더하게 됨

array([[10, 20, 30],
       [40, 50, 60]])

array([17, 17, 17])

array([[27, 37, 47],
       [57, 67, 77]])

In [ ]:
# 스칼라 곱이나 제곱도 연산 가능
arr2 * 10
arr2 ** 2

array([[100, 200, 300],
       [400, 500, 600]])

array([[ 100,  400,  900],
       [1600, 2500, 3600]])

In [34]:
ysArray = np.arange(10)
ysArray
ysArray[0]
ysArray[4]
ysArray[9]
ysArray[1:9]
ysArray[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.int64(0)

np.int64(4)

np.int64(9)

array([1, 2, 3, 4, 5, 6, 7, 8])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr2
arr2[1, :]
arr2[1, 2]

array([[10, 20, 30],
       [40, 50, 60]])

array([40, 50, 60])

np.int64(60)

In [49]:
ysArray = np.random.randn(3, 2) # 랜덤 값 생성
ysArray
ysArray[ysArray[:, 0] < 0, :]   # 0번째 열의 값이 0보다 작은 모든 값
# ysArray[ysArray[:, 1] < 0, :]   # 1번째 열의 값이 0보다 작은 모든 값



array([[ 1.0916097 ,  1.31866679],
       [ 1.18956283,  2.17445324],
       [ 0.0258411 , -0.02175138]])

array([], shape=(0, 2), dtype=float64)

In [ ]:
# invalid value로 인해 계산에 너무 오래 걸리면 RuntimeWarning 뜸
# 계산 불가한 원소는 nan으로 표시된다
np.abs(ysArray)     # 절대값
np.sqrt(ysArray)    # 제곱근
np.square(ysArray)  # 각 원소의 제곱
np.exp(ysArray)     # 각 원소의 지수
np.log(ysArray)     # 각 원소의 로그
np.log2(ysArray)    # 각 원소의 밑이 2인 로그

array([[1.0916097 , 1.31866679],
       [1.18956283, 2.17445324],
       [0.0258411 , 0.02175138]])

C:\Users\USER\AppData\Local\Temp\ipykernel_6588\2324324445.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ysArray)    # 제곱근


array([[1.04480127, 1.14833218],
       [1.09067082, 1.47460274],
       [0.16075166,        nan]])

array([[1.19161173e+00, 1.73888211e+00],
       [1.41505974e+00, 4.72824687e+00],
       [6.67762228e-04, 4.73122598e-04]])

array([[2.97906561, 3.73843395],
       [3.28564452, 8.79737372],
       [1.02617787, 0.97848347]])

C:\Users\USER\AppData\Local\Temp\ipykernel_6588\2324324445.py:6: RuntimeWarning: invalid value encountered in log
  np.log(ysArray)     # 각 원소의 로그


array([[ 0.08765339,  0.27662122],
       [ 0.17358587,  0.77677725],
       [-3.6557892 ,         nan]])

C:\Users\USER\AppData\Local\Temp\ipykernel_6588\2324324445.py:7: RuntimeWarning: invalid value encountered in log2
  np.log2(ysArray)    # 각 원소의 로그2값


array([[ 0.12645712,  0.39908006],
       [ 0.25043148,  1.12065268],
       [-5.27418894,         nan]])

In [66]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 8, 16, 32])
arr3 = np.array([3, 9, 27, 81, 243])
arr10 = np.array([1, 10, 100, 1000, 10000])
np.log(arr1)    # 자연 로그(자연 상수, 약 2.71828)
np.log2(arr2)   # 밑이 2인 이진로그

# 임의의 밑을 가진 로그 계산 → 수학 공식 참고
# log_a B = log_c B / log_c A

# 밑이 3인 로그 구하기
log_base_3 = np.log(arr3) / np.log(3)
log_base_3      # 및이 3인 로그

# 밑이 10인 로그(상용로그) 구하기
log_base_10  = np.log(arr10) / np.log(10)
log_base_10

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

array([1., 2., 3., 4., 5.])

array([1., 2., 3., 4., 5.])

array([0., 1., 2., 3., 4.])

In [ ]:
ysArray
np.sum(ysArray, axis = 0) # 0열의 합
np.sum(ysArray, axis = 1) # 1열의 합

array([[ 1.0916097 ,  1.31866679],
       [ 1.18956283,  2.17445324],
       [ 0.0258411 , -0.02175138]])

array([2.30701363, 3.47136865])

array([2.41027649, 3.36401607, 0.00408971])

np.float64(0.7648519522426621)

In [ ]:
np.std(ysArray) # 표준편차
np.var(ysArray) # 분산
np.min(ysArray) # 최소값
np.max(ysArray) # 최대값

np.float64(0.7648519522426621)

np.float64(0.5849985088494115)

np.float64(-0.021751381527769766)

np.float64(2.1744532355434534)

array([[ 0.0258411 , -0.02175138],
       [ 1.0916097 ,  1.31866679],
       [ 1.18956283,  2.17445324]])

array([[ 1.0916097 ,  1.31866679],
       [ 1.18956283,  2.17445324],
       [-0.02175138,  0.0258411 ]])

In [ ]:
ysArray
# 정렬
np.sort(ysArray, axis = 0) # 열마다 세로방향 정렬
np.sort(ysArray, axis = 1) # 행마다 가로방향 정렬

array([[ 1.0916097 ,  1.31866679],
       [ 1.18956283,  2.17445324],
       [ 0.0258411 , -0.02175138]])

array([[ 0.0258411 , -0.02175138],
       [ 1.0916097 ,  1.31866679],
       [ 1.18956283,  2.17445324]])

array([[ 1.0916097 ,  1.31866679],
       [ 1.18956283,  2.17445324],
       [-0.02175138,  0.0258411 ]])